/**
 * @name BackboneElement
 * @version R4
 * @author Claudia Alarcón Lazo
 */
export type BackboneElementType =
  | 'AccountCoverage'
  | 'AccountGuarantor'
  | 'AllergyIntoleranceReaction'
  | 'AppointmentParticipant'
  | 'AuditEventAgent'
  | 'AuditEventAgentNetwork'
  | 'AuditEventEntity'
  | 'AuditEventEntityDetail'
  | 'BundleEntry'
  | 'BundleEntryRequest'
  | 'BundleEntryResponse'
  | 'BundleEntrySearch'
  | 'BundleLink'
  | 'CarePlanActivity'
  | 'CarePlanActivityDetail'
  | 'CareTeamParticipant'
  | 'CompositionAttester'
  | 'CompositionEvent'
  | 'CompositionRelatesTo'
  | 'CompositionSection'
  | 'ConditionEvidence'
  | 'ConditionStage'
  | 'CoverageClass'
  | 'CoverageCostToBeneficiary'
  | 'CoverageCostToBeneficiaryException'
  | 'DiagnosticReportMedia'
  | 'EncounterClassHistory'
  | 'EncounterDiagnosis'
  | 'EncounterHospitalization'
  | 'EncounterLocation'
  | 'EncounterParticipant'
  | 'EncounterStatusHistory'
  | 'EpisodeOfCareDiagnosis'
  | 'EpisodeOfCareStatusHistory'
  | 'FamilyMemberHistoryCondition'
  | 'GoalTarget'
  | 'GroupCharacteristic'
  | 'GroupMember'
  | 'HealthcareServiceAvailableTime'
  | 'HealthcareServiceEligibility'
  | 'HealthcareServiceNotAvailable'
  | 'LocationPosition'
  | 'ObservationComponent'
  | 'ObservationReferenceRange'
  | 'OperationOutcomeIssue'
  | 'OrganizationContact'
  | 'PatientCommunication'
  | 'PatientContact'
  | 'PatientLink'
  | 'PersonLink'
  | 'PractitionerQualification'
  | 'PractitionerRoleAvailableTime'
  | 'PractitionerRoleNotAvailable'
  | 'ProcedureFocalDevice'
  | 'ProcedurePerformer'
  | 'RelatedPersonCommunication'
  | 'TaskInput'
  | 'TaskOutput'
  | 'TaskRestriction'
  | 'Timing';
