/**
 * @name DataType
 * @description A version specific list of the data types defined by the FHIR specification for use as an element type (any of the FHIR defined data types).
 * @description Address | Age | Annotation | Attachment | BackboneElement | CodeableConcept | Coding | ContactDetail | ContactPoint | Contributor | Count | DataRequirement | Distance | Dosage | Duration | Element | ElementDefinition | Expression | Extension | HumanName | Identifier | MarketingStatus | Meta | Money | MoneyQuantity | Narrative | ParameterDefinition | Period | Population | ProdCharacteristic | ProductShelfLife | Quantity | Range | Ratio | Reference | RelatedArtifact | SampledData | Signature | SimpleQuantity | SubstanceAmount | Timing | TriggerDefinition | UsageContext | base64Binary | boolean | canonical | code | date | dateTime | decimal | id | instant | integer | markdown | oid | positiveInt | string | time | unsignedInt | uri | url | uuid | xhtml
 * @see <a href="https://hl7.org/fhir/R4/valueset-data-types.html">DataType</a>
 * @version R4
 * @author Roberto Araneda Espinoza
 */
export type DataTypeType =
  | 'Address'
  | 'Age'
  | 'Annotation'
  | 'Attachment'
  | 'BackboneElement'
  | 'CodeableConcept'
  | 'Coding'
  | 'ContactDetail'
  | 'ContactPoint'
  | 'Contributor'
  | 'Count'
  | 'DataRequirement'
  | 'Distance'
  | 'Dosage'
  | 'Duration'
  | 'Element'
  | 'ElementDefinition'
  | 'Expression'
  | 'Extension'
  | 'HumanName'
  | 'Identifier'
  | 'MarketingStatus'
  | 'Meta'
  | 'Money'
  | 'MoneyQuantity'
  | 'Narrative'
  | 'ParameterDefinition'
  | 'Period'
  | 'Population'
  | 'ProdCharacteristic'
  | 'ProductShelfLife'
  | 'Quantity'
  | 'Range'
  | 'Ratio'
  | 'Reference'
  | 'RelatedArtifact'
  | 'SampledData'
  | 'Signature'
  | 'SimpleQuantity'
  | 'SubstanceAmount'
  | 'Timing'
  | 'TriggerDefinition'
  | 'UsageContext'
  | 'base64Binary'
  | 'boolean'
  | 'canonical'
  | 'code'
  | 'date'
  | 'dateTime'
  | 'decimal'
  | 'id'
  | 'instant'
  | 'integer'
  | 'markdown'
  | 'oid'
  | 'positiveInt'
  | 'string'
  | 'time'
  | 'unsignedInt'
  | 'uri'
  | 'url'
  | 'uuid'
  | 'xhtml';
