export type ResourceType =
"Account" |
"ActivityDefinition" |
"AdverseEvent" |
"AllergyIntolerance" |
"Appointment" |
"AppointmentResponse" |
"AuditEvent" |
"Basic" |
"Binary" |
"BiologicallyDerivedProduct" |
"BodyStructure" |
"Bundle" |
"CapabilityStatement" |
"CarePlan" |
"CareTeam" |
"CatalogEntry" |
"ChargeItem" |
"ChargeItemDefinition" |
"Claim" |
"ClaimResponse" |
"ClinicalImpression" |
"CodeSystem" |
"Communication" |
"CommunicationRequest" |
"CompartmentDefinition" |
"Composition" |
"ConceptMap" |
"Condition" |
"Consent" |
"Contract" |
"Coverage" |
"CoverageEligibilityRequest" |
"CoverageEligibilityResponse" |
"DetectedIssue" |
"Device" |
"DeviceDefinition" |
"DeviceMetric" |
"DeviceRequest" |
"DeviceUseStatement" |
"DiagnosticReport" |
"DocumentManifest" |
"DocumentReference" |
"DomainResource" |
"EffectEvidenceSynthesis" |
"Encounter" |
"Endpoint" |
"EnrollmentRequest" |
"EnrollmentResponse" |
"EpisodeOfCare" |
"EventDefinition" |
"Evidence" |
"EvidenceVariable" |
"ExampleScenario" |
"ExplanationOfBenefit" |
"FamilyMemberHistory" |
"Flag" |
"Goal" |
"GraphDefinition" |
"Group" |
"GuidanceResponse" |
"HealthcareService" |
"ImagingStudy" |
"Immunization" |
"ImmunizationEvaluation" |
"ImmunizationRecommendation" |
"ImplementationGuide" |
"InsurancePlan" |
"Invoice" |
"Library" |
"Linkage" |
"List" |
"Location" |
"Measure" |
"MeasureReport" |
"Media" |
"Medication" |
"MedicationAdministration" |
"MedicationDispense" 
