/**
 * @name DataType
 * @description A version specific list of the data types defined by the FHIR specification for use as an element type (any of the FHIR defined data types).
 * @description Address | Age | Annotation | Attachment | BackboneElement | CodeableConcept | Coding | ContactDetail | ContactPoint | Contributor | Count | DataRequirement | Distance | Dosage | Duration | Element | ElementDefinition | Expression | Extension | HumanName | Identifier | MarketingStatus | Meta | Money | MoneyQuantity | Narrative | ParameterDefinition | Period | Population | ProdCharacteristic | ProductShelfLife | Quantity | Range | Ratio | Reference | RelatedArtifact | SampledData | Signature | SimpleQuantity | SubstanceAmount | Timing | TriggerDefinition | UsageContext | base64Binary | boolean | canonical | code | date | dateTime | decimal | id | instant | integer | markdown | oid | positiveInt | string | time | unsignedInt | uri | url | uuid | xhtml
 * @see <a href="https://hl7.org/fhir/R4/valueset-data-types.html">DataType</a>
 * @version R4
 * @author Roberto Araneda Espinoza
 */
export enum DataTypeEnum {
  ADDRESS = 'Address',
  AGE = 'Age',
  ANNOTATION = 'Annotation',
  ATTACHMENT = 'Attachment',
  BACKBONE_ELEMENT = 'BackboneElement',
  CODEABLE_CONCEPT = 'CodeableConcept',
  CODING = 'Coding',
  CONTACT_DETAIL = 'ContactDetail',
  CONTACT_POINT = 'ContactPoint',
  CONTRIBUTOR = 'Contributor',
  COUNT = 'Count',
  DATA_REQUIREMENT = 'DataRequirement',
  DISTANCE = 'Distance',
  DOSAGE = 'Dosage',
  DURATION = 'Duration',
  ELEMENT = 'Element',
  ELEMENT_DEFINITION = 'ElementDefinition',
  EXPRESSION = 'Expression',
  EXTENSION = 'Extension',
  HUMAN_NAME = 'HumanName',
  IDENTIFIER = 'Identifier',
  MARKETING_STATUS = 'MarketingStatus',
  META = 'Meta',
  MONEY = 'Money',
  MONEY_QUANTITY = 'MoneyQuantity',
  NARRATIVE = 'Narrative',
  PARAMETER_DEFINITION = 'ParameterDefinition',
  PERIOD = 'Period',
  POPULATION = 'Population',
  PROD_CHARACTERISTIC = 'ProdCharacteristic',
  PRODUCT_SHELF_LIFE = 'ProductShelfLife',
  QUANTITY = 'Quantity',
  RANGE = 'Range',
  RATIO = 'Ratio',
  REFERENCE = 'Reference',
  RELATED_ARTIFACT = 'RelatedArtifact',
  SAMPLE_DATA = 'SampledData',
  SIGNATURE = 'Signature',
  SIMPLE_QUANTITY = 'SimpleQuantity',
  SUBSTANCE_AMOUNT = 'SubstanceAmount',
  TIMING = 'Timing',
  TRIGGER_DEFINITION = 'TriggerDefinition',
  USAGE_CONTEXT = 'UsageContext',
  BASE64_BINARY = 'base64Binary',
  BOOLEAN = 'boolean',
  CANONICAL = 'canonical',
  CODE = 'code',
  DATE = 'date',
  DATE_TIME = 'dateTime',
  DECIMAL = 'decimal',
  ID = 'id',
  INSTANT = 'instant',
  INTEGER = 'integer',
  MARKDOWN = 'markdown',
  OID = 'oid',
  POSITIVE_INT = 'positiveInt',
  STRING = 'string',
  TIME = 'time',
  UNSIGNED_INT = 'unsignedInt',
  URI = 'uri',
  URL = 'url',
  UUID = 'uuid',
  XHTML = 'xhtml',
}
