export enum EventTimingEnum {
  MORN = 'MORN',
  MORN_EARLY = 'MORN.early',
  MORN_LATE = 'MORN.late',
  NOON = 'NOON',
  AFT = 'AFT',
  AFT_EARLY = 'AFT.early',
  AFT_LATE = 'AFT.late',
  EVE = 'EVE',
  EVE_EARLY = 'EVE.early',
  EVE_LATE = 'EVE.late',
  NIGHT = 'NIGHT',
  PHS = 'PHS',
  HS = 'HS',
  WAKE = 'WAKE',
  C = 'C',
  CM = 'CM',
  CD = 'CD',
  CV = 'CV',
  AC = 'AC',
  ACM = 'ACM',
  ACD = 'ACD',
  ACV = 'ACV',
  PC = 'PC',
  PCM = 'PCM',
  PCD = 'PCD',
  PCV = 'PCV',
}
