/**
 * Enum for FHIR resources
 */
export enum ResourceEnum {
  PATIENT = 'Patient',
  ORGANIZATION = 'Organization',
  ENDPOINT = 'Endpoint',
  PERSON = 'Person',
  PRACTITIONER = 'Practitioner',
  PRACTITIONER_ROLE = 'PractitionerRole',
  RELATED_PERSON = 'RelatedPerson',
  GROUP = 'Group',
  LOCATION = 'Location',
  BUNDLE = 'Bundle',
  CARE_TEAM = 'CareTeam',
  ENCOUNTER = 'Encounter',
  SPECIMEN = 'Specimen',
  MEDICATION = 'Medication',
  DEVICE = 'Device',
  DOCUMENT_REFERENCE = 'DocumentReference',
  COMPOSITION = 'Composition',
  CARE_PLAN = 'CarePlan',
  CONDITION = 'Condition',
  PROCEDURE = 'Procedure',
  OBSERVATION = 'Observation',
  IMMUNIZATION = 'Immunization',
  HEALTHCARE_SERVICE = 'HealthcareService',
  SUBSTANCE = 'Substance',
  MESSAGE_HEADER = 'MessageHeader',
  MEDICATION_STATEMENT = 'MedicationStatement',
  ACCOUNT = 'Account',
  COVERAGE = 'Coverage',
  CLAIM = 'Claim',
  AUDIT_EVENT = 'AuditEvent',
  ALLERGY_INTOLERANCE = 'AllergyIntolerance',
  APPOINTMENT = 'Appointment',
  APPOINTMENT_RESPONSE = 'AppointmentResponse',
  BASIC = 'Basic',
  BINARY = 'Binary',
}
